---
version: '3.8'
services:
  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - JDBC_PARAMS="useSSL=false"
      - DB_PASSWORD=keycloak
      - PROXY_ADDRESS_FORWARDING=true
      - DEBUG=false
      - DEBUG_PORT='*:8787'
      - KEYCLOAK_LOGLEVEL=ERROR
      - ROOT_LOGLEVEL=ERROR
      - JAVA_OPTS=-server -Xms1024m -Xmx4096m -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=1024m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.naming/com.sun.jndi.ldap=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.util.concurrent=ALL-UNNAMED --add-opens=java.management/javax.management=ALL-UNNAMED --add-opens=java.naming/javax.naming=ALL-UNNAMED
    depends_on:
      - postgres
    networks:
      - keycloak-networks
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
    networks:
      - keycloak-networks
    volumes:
      - /var/local/rcms/db:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
  proxy:
    image: docker.io/library/ui
    container_name: proxy
    logging:
      driver: json-file
      options:
        max-size: "10m"
    ports:
      - "80:80"
      - "443:443"
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1024M
        reservations:
          cpus: '1'
          memory: 512M
    depends_on:
      - keycloak
    networks:
      - keycloak-networks

networks:
  keycloak-networks:
    name: keycloak-networks
    driver: bridge
